site_name: My Great Divide 2024
site_description: "riding the Great Divide Mountain Bike Route"
site_url: https://divide.atarigo.net/

theme:
  name: material
 
extra:
  analytics:
    provider: google
    property: G-CR3FZ4XFFT

plugins:
  - projects

